### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by qwandor** [ruediger/cloudbbq2-rs#1]
I recently got a cooking thermometer that appears to be compatible with this, and I'd like to a play around with your code and possibly send some pull requests. However, before I do that, I'd like to know what license it's under. Can you add a `LICENSE` file and specify the license in `Cargo.toml`? Apache 2 + MIT dual licensing seems to be pretty common in the Rust ecosystem, so that would be a convenient choice.

**Comment by ruediger** [comment]
Done.

I didn't get very far with this code yet and currently don't have access to my thermometer.  I hope this is useful though. I found https://gist.github.com/uucidl/b9c60b6d36d8080d085a8e3310621d64 which describes the interface. Although it looked like my thermometer had a slightly different init sequence.

**Comment by qwandor** [comment]
Great, thanks! I'm working on getting our BlueZ wrapper code ready to release as a crate after all.
